name: Backend Health Check

on:
  schedule:
    - cron: "2,7,12,17,22,27,32,37,42,47,52,57 * * * *"
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check Render backend
        run: |
          curl --fail --max-time 30 \
          https://portfolio-dux4.onrender.com/health
